-- ============================================================
-- 559 Flawless — 017: real Rhonda Allison retail catalogue
--
-- 42 products taken from the studio's own storefront
-- (ramarketplace.com/store/559flawless), each linking to ITS OWN product page
-- rather than the generic cart.
--
-- Images (40 of 42) are the official Rhonda Allison product photography from
-- the brand's CDN. The marketplace storefront itself publishes no images — its
-- <img> tags are literally empty — so there was nothing to take from there.
-- The two without images are gauze pads, which the brand does not photograph.
--
-- These are externally fulfilled: the marketplace takes payment and ships. So
-- external_url is set, stock stays 0, and the shop links out instead of adding
-- to a cart. Price is deliberately NOT stored — the marketplace owns it, and a
-- figure here that drifts from the real checkout price is worse than none.
--
-- Idempotent: re-running refreshes name, description, image, link and category.
-- ============================================================

-- Clear the earlier placeholder rows that pointed at the generic cart.
delete from public.products
where external_url like '%ramarketplace.com%'
  and external_url not like '%/product/%';

insert into public.products
  (sku, name, slug, category_id, brand_id, description, image_url, external_url,
   is_retail, is_professional, price_cents, stock_qty, sort_order)
select
  v.sku, v.name, v.slug,
  (select id from public.product_categories where slug = v.category_slug),
  (select id from public.brands where slug = 'rhonda-allison'),
  v.description, v.image_url, v.external_url,
  true, false, 0, 0, v.sort_order
from (values
  ('RA-PUMPKINLACTICCLEANSE', 'Pumpkin Lactic Cleanse', 'pumpkin-lactic-cleanse', 'cleansers-scrubs', 'The aroma will hook you! A long-standing pro-youth favorite, this lactic acid-based cleanser increases cell turnover and hydration while smoothing skin’s texture. Lactic Acid Softens Texture Pumpkin Seed Oil Delivers Antioxidants Stimulates Collagen Support Leaves Skin Nourished and Radiant TIP: Mix with Gentle Peptide Cleanse to reduce dryness', 'https://cdn.shopify.com/s/files/1/0079/2828/3249/files/PUMPKIN_LACTIC_CLEANSE_120ml.png?v=1769639144', 'https://ramarketplace.com/store/559flawless/product/pumpkin-lactic-cleanse', 0),
  ('RA-BETABRIGHTCLEANSE', 'Beta Bright Cleanse', 'beta-bright-cleanse', 'cleansers-scrubs', 'This anti-inflammatory cleanser provides antioxidants, antibacterial and calming support. Salicylic acid and the heart of green tea softens, protects and provides healing to the skin. Excellent for pigmentation caused by injuries/wounds. Deep Pore Cleansing Reduces Redness Protects Against Over-Drying', 'https://cdn.shopify.com/s/files/1/0079/2828/3249/files/BETA_BRIGHT_CLEANSE_120ml.png?v=1769804321', 'https://ramarketplace.com/store/559flawless/product/beta-bright-cleanse', 1),
  ('RA-GREENTEABETACLEANSE', 'Green Tea Beta Cleanse', 'green-tea-beta-cleanse', 'cleansers-scrubs', 'A powerful acne cleanser comprised of green tea and salicylic acid, created to target bacteria, inflammation and exfoliation all in one! A great choice for most acne-prone skin, allowing the soothing properties of the heart of green tea to support without irritation. Powerful Antiseptic Support Reduces Inflammation Increases Cellular Exfoliation Softens Texture TIP: For dry acne, alternate with Pu', 'https://cdn.shopify.com/s/files/1/0079/2828/3249/files/GREEN_TEA_BETA_CLEANSE_120ml.png?v=1765906629', 'https://ramarketplace.com/store/559flawless/product/green-tea-beta-cleanse', 2),
  ('RA-2X2GAUZEPADS200COUNT', '2x2 Gauze Pads (200 count)', '2x2-gauze-pads-200-count', 'cleansers-scrubs', null, null, 'https://ramarketplace.com/store/559flawless/product/2x2-gauze-pads-200-count', 3),
  ('RA-ALLPURPOSECLEANSINGPADS', 'All Purpose Tonic Pads', 'all-purpose-cleansing-pads', 'toners', 'A blend of salicylic acid and totarol help reduce bacteria, oils and residue from skin. Skin is left feeling refreshed and clean. Perfect to use after workouts or sporting practice. Eliminates Bacteria Reduces Lipids Provides Antioxidant Support Perfect for Teens & Athletes TIP: Pairs well with Hyaluronic Tonic and eZinc Protection for a quick post-workout regimen', 'https://cdn.shopify.com/s/files/1/0079/2828/3249/products/AP_TONIC_PADS_60ct.png?v=1649361796', 'https://ramarketplace.com/store/559flawless/product/all-purpose-cleansing-pads', 4),
  ('RA-ANTIOXAHATONIC', 'Antiox AHA Tonic', 'antiox-aha-tonic', 'toners', 'This active AHA toner will bring balance and relief to hormonal breakouts and excessive lipid production with a synergistic blend of salicylic acid, lactic acid and powerful antioxidants. Reduces Excess Sebum Dissolves Dead Skin Cell Buildup Firms, Tones & Smoothes Texture Soothes Inflamed Acne Conditions TIP: Great to use as spot treatment for mature acne. Mix into Purifying Gel Cleanse for added', 'https://cdn.shopify.com/s/files/1/0079/2828/3249/files/ANTIOX_AHA_TONIC_120ml_0735a67e-a11e-4a6b-bc7b-8b5fa977808d.png?v=1769632815', 'https://ramarketplace.com/store/559flawless/product/antiox-aha-tonic', 5),
  ('RA-ANTIOXDEFENDTONIC', 'Antiox Defend Tonic', 'antiox-defend-tonic', 'toners', 'Protect pro-youth skin against damaging effects of the environment, with a daily dose of powerful antioxidants. Super oxide dismutase and L-glutathione protect against free-radical damage while mandelic acid softens texture and stimulates collagen. Reduces Oxidative Stress Softens Texture Stimulates Collagen Synthesis TIP: Pair with Mandelic Rejuvenator to increase benefits', 'https://cdn.shopify.com/s/files/1/0079/2828/3249/files/ANTIOX_DEFEND_TONIC_120ml.png?v=1769639314', 'https://ramarketplace.com/store/559flawless/product/antiox-defend-tonic', 6),
  ('RA-ARENEW', '&quot;A&quot; Renew +', 'a-renew', 'correctives', 'A lifestyle-friendly, encapsulated vitamin A formulated with reparative stem cells to synthesize collagen and elastin production, increase cellular turnover and repair damaged cells. An effective rebuilding and strengthening serum for lightening and brightening the skin. Reduces Inflammation Boosts Surface Exfoliation Strengthens Skin TIP - Combine 1 pump with other correctives to strengthen overa', 'https://cdn.shopify.com/s/files/1/0079/2828/3249/files/A_RENEW_30ml_T.png?v=1769804490', 'https://ramarketplace.com/store/559flawless/product/a-renew', 7),
  ('RA-AHAREFINEGEL', 'AHA Refine Gel', 'aha-refine-gel', 'correctives', 'A powerful AHA combination of lactic and glycolic acids to enhance the break down of cellular build up for a softened and clear complexion. Boosts Cellular Exfoliation Loosens Micromedones Smoothes Texture TIP: Mix into a moisturizer like Mandelic Replenish to introduce to skin or increase use', 'https://cdn.shopify.com/s/files/1/0079/2828/3249/files/AHA_REFINE_GEL_15ml_5a79be7b-d6d2-453e-889e-cf9a2a5daf13.png?v=1769634034', 'https://ramarketplace.com/store/559flawless/product/aha-refine-gel', 8),
  ('RA-BHAREFINEGEL', 'BHA Refine Gel', 'bha-refine-gel', 'correctives', 'This powerful salicylic & azelaic acid corrective reduces cellular buildup, smoothes texture, fights bacteria and inflammation. Excellent for congested skin. Reduces Congestion & Impactions Minimizes Scarring Balances Oil Gives a More Refined Complexion TIP: Rotate every few months with AHA Refine Gel . Use for potent spot treatment.', 'https://cdn.shopify.com/s/files/1/0079/2828/3249/files/BHA_REFINE_GEL_15ml_4069ba38-da8d-47b2-a32b-18d947c83aa3.png?v=1769633986', 'https://ramarketplace.com/store/559flawless/product/bha-refine-gel', 9),
  ('RA-BLEMISHSERUM', 'Blemish Serum', 'blemish-serum', 'correctives', 'Blemish Serum is a blend of natural ingredients that support problematic skin conditions gently and effectively, enhancing the appearance of purity and clearing of skin blemishes. A versatile product that may be used alone, to spot treat lesions, blended with brightening products or layered under masks.', 'https://cdn.shopify.com/s/files/1/0079/2828/3249/products/Sq60_BLEMISHSERUM.png?v=1611966477', 'https://ramarketplace.com/store/559flawless/product/blemish-serum', 10),
  ('RA-BALANCINGCOCKTAIL', 'Balancing Cocktail', 'balancing-cocktail', 'building-strengthening', 'A refined blend of grape seed oil combined with wild yam provide light hydration and reduce inflammation for hormonally challenged skins, without concern of an oily residue or pores becoming clogged. Contains Naturally Occurring Progesterone Balances Skin Increases Oxygen to Pores Antioxidant Support TIP: Use as a hydrator and hormonal balancer.', 'https://cdn.shopify.com/s/files/1/0079/2828/3249/files/BALANCING_COCKTAIL_30ml_T_107a2691-3c26-491f-ba0c-8f406f8fe948.png?v=1769634242', 'https://ramarketplace.com/store/559flawless/product/balancing-cocktail', 11),
  ('RA-AGELESS', 'AgeLess', 'ageless', 'building-strengthening', 'It''s time to Age less! Our holistic blend of antioxidants reduces damage and inflammation caused from free radicals, while mimosa bark and plantain stem cells strengthen skin, replacing damaged collagen. This powerful serum addresses the negative effects of glycation and brightens skin tone for a vibrant and luminous look. Anti-Glycation Powerhouse Brighten Skin Tone Soften Stiff Proteins Boost Pr', 'https://cdn.shopify.com/s/files/1/0079/2828/3249/files/AGE_LESS_30ml_T.png?v=1769705306', 'https://ramarketplace.com/store/559flawless/product/ageless', 12),
  ('RA-AMINOPEPTIDESERUM', 'Amino Peptide Serum', 'amino-peptide-serum', 'building-strengthening', 'Amino Peptide Serum offers the benefit of peptide support that includes our freezing peptide and line minimizing peptides combined with our Advanced Moisture Complex for the ultimate in hydration. All skin types will benefit from this elite rejuvenator. Amino Peptide Serum is a superior preventative and ageless serum reducing the appearance of wrinkles caused by the contraction of facial muscles (', 'https://cdn.shopify.com/s/files/1/0079/2828/3249/products/Sq60_AMINOPEPTIDESERUM.png?v=1611968368', 'https://ramarketplace.com/store/559flawless/product/amino-peptide-serum', 13),
  ('RA-ANTIOX18COMPLEX', 'Antiox 18  Complex', 'antiox-18-complex', 'building-strengthening', 'One of our first antioxidant formulas, continues to be a Pro-Youth Essential. It contains a blend of 18 powerful antioxidants, including glutathione (L), resveratrol and green tea. Notice firming and toning action within the first 2 weeks using this hydrating, biopeptide formula! Decrease Free Radicals Reduce Oxidative Stress - such as toxic environments or UV Exposure Increase in Firmness Healthy', 'https://cdn.shopify.com/s/files/1/0079/2828/3249/files/ANTIOX_18_COMPLEX_50ml_T.png?v=1769705287', 'https://ramarketplace.com/store/559flawless/product/antiox-18-complex', 14),
  ('RA-ALOEMATTEMOISTURECREAM', 'Aloe Matte Moisture Cream', 'aloe-matte-moisture-cream', 'moisturizers-hydrators', 'Providing natural daytime protection from UV rays, Aloe Matte Moisture Cream balances excess oil and supplies water-binding moisture with healing Aloe Vera and hydrating Sodium Hyaluronate (L), the purest form of hyaluronic acid. This light, creamy formula is ideal for problematic skin types, especially due to the combination healing, moisturizing and antimicrobial factors. Not recommended as a su', 'https://cdn.shopify.com/s/files/1/0079/2828/3249/products/Sq120_AloeMatteMoistureCream.png?v=1611963398', 'https://ramarketplace.com/store/559flawless/product/aloe-matte-moisture-cream', 15),
  ('RA-AMINOPEPTIDEHYDRATION', 'Amino Peptide Hydration', 'amino-peptide-hydration', 'moisturizers-hydrators', 'A lightweight, collagen-boosting hydrator that uses peptides and advanced moisturizing complexes to maintain skin’s supple appearance and elasticity. Assists in Age Prevention Potent Peptide Blend Increase in Collagen Synthesis Boosts Hyaluronic Acid TIP: Perfect age-prevention moisturizer when paired with Mandelic Rejuvenator', 'https://cdn.shopify.com/s/files/1/0079/2828/3249/files/AMINO_PEPTIDE_HYDRATION_50ml_T.png?v=1769706517', 'https://ramarketplace.com/store/559flawless/product/amino-peptide-hydration', 16),
  ('RA-BRIGHTENINGCREAMENHANCED', 'Brightening Cream Enhanced', 'brightening-cream-enhanced', 'moisturizers-hydrators', 'A synergistic blend of natural brightening ingredients to support all forms of pigmentation, while providing renewed radiance and creamy hydration. Improves Skin''s Luminosity Brightens & Evens Ton Using Next Generation Lighteners Moisturizing Benefits TIP: Add 1 pump of Radiant Renewal Serum for additional antioxidant and strengthening support.', 'https://cdn.shopify.com/s/files/1/0079/2828/3249/files/BRIGHTENING_CREAM_ENHANCED_50ml_T.png?v=1769804939', 'https://ramarketplace.com/store/559flawless/product/brightening-cream-enhanced', 17),
  ('RA-DROPOFESSENCE', 'Drop of Essence', 'drop-of-essence', 'moisturizers-hydrators', 'The composition and molecular structure of Omega 6 essential fatty acid is similar to human lipid and is recommend not only as part of post- peel care but as a hydrating, daily moisturizer. A superior carrier agent to facilitate the penetration of other active ingredients for enhanced product performance. A great choice for aiding skin in healing of burns, shingles and cold sores. Increases skin t', 'https://cdn.shopify.com/s/files/1/0079/2828/3249/products/Sq120_DropOfEssence.png?v=1611963783', 'https://ramarketplace.com/store/559flawless/product/drop-of-essence', 18),
  ('RA-ALOEZYME', 'Aloe-Zyme', 'aloe-zyme', 'enzymes-masks', 'A weekly exfoliation treatment with pineapple and papaya enzymes that gently dissolves cellular build up to reveal smooth, soft, glowing skin. Safe for the even the most sensitive, acne-prone skin. Liquifying Gommage Enzyme Easy to Use Gently Digests Cellular Buildup Increases Oxygenation to Pores TIP: Make it a full treatment and finish with Wasabi Mask .', 'https://cdn.shopify.com/s/files/1/0079/2828/3249/files/ALOE_ZYME_50ml_T_311670c4-1dac-4da0-a1e8-ba17ae5a1e06.png?v=1769634923', 'https://ramarketplace.com/store/559flawless/product/aloe-zyme', 19),
  ('RA-CHERRYJUBILEEENZYME', 'Cherry Jubilee Enzyme', 'cherry-jubilee-enzyme', 'enzymes-masks', 'Cherry Jubilee is a potent antioxidant rejuvenator. Everyone is sure to “ooh and ahh” over the enticing cherry aroma, and enjoy the healthy glow the cherry enzymes leave on the skin. The primary benefit of this enzyme is the natural polyphenols (flavonoids) that are incredibly rich in antioxidants. This formula contains potent pro-youth value that mimics the strength of lactic acid and helps provi', 'https://cdn.shopify.com/s/files/1/0079/2828/3249/products/CHERRYJUBILEEENZYME.png?v=1611957505', 'https://ramarketplace.com/store/559flawless/product/cherry-jubilee-enzyme', 20),
  ('RA-CHOCOLATEANTIOXMASK', 'Chocolate Antiox Mask', 'chocolate-antiox-mask', 'enzymes-masks', 'A therapeutic mask delivering potent antioxidants from cocoa extract, cranberry and camu camu. This decadent, tingling experience will leave skin revitalized and replenished. Protects Against Cell Damage Detoxifies Skin Brightens Complexion TIP: Apply Pure Grape Seed Elixir before mask to reduce stimulating sensations and boost hydration', 'https://cdn.shopify.com/s/files/1/0079/2828/3249/files/CHOCOLATE_ANTIOX_MASK_50ml_W.png?v=1769706994', 'https://ramarketplace.com/store/559flawless/product/chocolate-antiox-mask', 21),
  ('RA-CLEARBRIGHTZYME', 'Clear Bright Zyme', 'clear-bright-zyme', 'enzymes-masks', 'This weekly enzyme utilizes the power of papaya to reduce cellular buildup, along with salicylic acid for antibacterial support. Azelaic Acid lessens pigmentation Softens Texture & Evens Skin Tone Decreases Bacteria & Inflammation Reduces Cellular Buildup TIP: For dry acne skin, combine with Cooling Relief Mask for additional hydration.', 'https://cdn.shopify.com/s/files/1/0079/2828/3249/products/CLEAR_BRIGHT_ZYME_50ml_W_1cb481d1-f9bd-4390-a3b4-544eae8491ec.png?v=1662590435', 'https://ramarketplace.com/store/559flawless/product/clear-bright-zyme', 22),
  ('RA-4X4GAUZEPADS200COUNT', '4x4 Gauze Pads (200 count)', '4x4-gauze-pads-200-count', 'systems-collections', null, null, 'https://ramarketplace.com/store/559flawless/product/4x4-gauze-pads-200-count', 23),
  ('RA-AGEREVERSALSYSTEMNORMALT', 'Age Reversal System - Normal to Dry Skin', 'age-reversal-system-normal-to-dry-skin', 'systems-collections', 'Reverse and slow the signs of skin aging! Our Age Reversal Collection for Normal to Dry Skin contains the most cutting-edge, intelligent, result-focused skin care ingredients, such as peptides, stem cells, encapsulated vitamin A, anti-glycation complexes and holistic antioxidants to reduce inflammation and wrinkles, boost collagen synthesis and reverse cellular damage to transform your skin. Simpl', 'https://cdn.shopify.com/s/files/1/0079/2828/3249/files/AGE_REVERSAL_TVL4_fab675e5-a481-4db9-940a-7fbcf0b951ad.png?v=1785274038', 'https://ramarketplace.com/store/559flawless/product/age-reversal-system-normal-to-dry-skin', 24),
  ('RA-AGEREVERSALSYSTEMSENSITI', 'Age Reversal System - Sensitive Skin', 'age-reversal-system-sensitive-skin', 'systems-collections', 'Reverse and slow the signs of skin aging! Our Age Reversal Collection for Sensitive Skin contains the most soothing, yet cutting-edge, intelligent, pro-youth skin care ingredients to get the results you’re looking for. Transform your skin using holistic antioxidants, strengthening botanicals, life-style friendly vitamin A, stem cells and biopeptides and reduce inflammation and fine lines, increase', 'https://cdn.shopify.com/s/files/1/0079/2828/3249/files/AGE_REVERSAL_SENSITIVE_TVL4.png?v=1769708173', 'https://ramarketplace.com/store/559flawless/product/age-reversal-system-sensitive-skin', 25),
  ('RA-COLLAGENSNAPBACK', 'Collagen Snap Back', 'collagen-snap-back', 'duos', 'Snap back youthful skin by capturing the power of vitamins C and A along with pro youth peptides for 24-hour collagen support. Using the 20% C-power of L-ascorbic acid for AM strengthening and reconstructing retinal for PM rejuvenation, minimize wrinkles and fine lines, plump and firm, increase hydration and brighten skin tone for younger, healthier-looking skin. COLLECTION INCLUDES: C-Peptide Com', 'https://cdn.shopify.com/s/files/1/0079/2828/3249/files/COLLAGEN_SNAP_BACK_DUO.png?v=1769707412', 'https://ramarketplace.com/store/559flawless/product/collagen-snap-back', 26),
  ('RA-DAILYDOSE', 'Daily Dose', 'daily-dose', 'duos', 'Strengthen, renew and return skin’s youthful complexion with a daily dose of vitamins to nourish and brighten dull, depleted skin. With the added benefits of growth factor to rejuvenate strong, healthy cells, skin will look vibrant, revitalized and years younger. COLLECTION INCLUDES: Bio 53 Matrix 15ml Vita 10 Complex 30ml', 'https://cdn.shopify.com/s/files/1/0079/2828/3249/files/DAILY_DOSE_DUO.png?v=1769707708', 'https://ramarketplace.com/store/559flawless/product/daily-dose', 27),
  ('RA-ELIMINATEHYDRATE', 'Eliminate + Hydrate', 'eliminate-hydrate', 'duos', 'Eliminate blemishes while keeping skin soothed and hydrated. Blemish Serum is a daily spot treatment with a potent blend of antibacterials and healing ingredients that enhances purity and reduces problematic areas. Partnered with Hyaluronic Tonic, a hydrating toner that uses heavy water and cucumber, this powerful duo will keep skin clear and refreshed. SYSTEM INCLUDES: Blemish Serum Hyaluronic To', 'https://cdn.shopify.com/s/files/1/0079/2828/3249/files/ELIMINATE_HYDRATE_DUO.png?v=1769637289', 'https://ramarketplace.com/store/559flawless/product/eliminate-hydrate', 28),
  ('RA-FADEGLOW', 'Fade & Glow', 'fade-glow', 'duos', 'Watch melasma, age spots and PIH fade away and leave skin glowing with this potent pigmentation reduction duo. Using a highly effective, non-hydroquinone lightening concentrate to spot treat and the hydrating, cell-strengthening support from epidermal growth factor, skin will be left brighter with a more even complexion and radiant tone. SYSTEM INCLUDES: Naturalé Mega Brightening Serum Radiant Ren', 'https://cdn.shopify.com/s/files/1/0079/2828/3249/files/FADE_GLOW_DUO.png?v=1769805312', 'https://ramarketplace.com/store/559flawless/product/fade-glow', 29),
  ('RA-EZINCPROTECTIONSPF22', 'Zinc Relief', 'ezinc-protection-spf-22', 'sun-protection', 'The zinc oxide complex in eZinc Protection SPF22 makes this formula a highly protective topical, giving skin much needed protection from the elements and UV rays without leaving the skin white or pasty. A light, pro-youth moisturizing cream that may be used day and night, this face and body mineral emulsion provides strong antioxidant benefits, soothing, healing support and is especially suited fo', 'https://cdn.shopify.com/s/files/1/0079/2828/3249/products/960x960R214eZinc.png?v=1594132382', 'https://ramarketplace.com/store/559flawless/product/ezinc-protection-spf-22', 30),
  ('RA-DAYTIMEDEFENSE', 'Daytime Defense', 'daytime-defense', 'sun-protection', 'This water-resistant, ultra-clean outdoor topical , with a natural sun protection factor equivalent to a SPF 30, is safe for all skin types, including babies . Daytime Defense provides a natural sun barrier using zinc oxide, shielding skin from harmful UVA and UVB rays. Botanical extracts boost antioxidant protection and antimicrobial support while delivering soothing, healing benefits and reducin', 'https://cdn.shopify.com/s/files/1/0079/2828/3249/files/DAYTIME_DEFENSE_30ml_W.png?v=1769714523', 'https://ramarketplace.com/store/559flawless/product/daytime-defense', 31),
  ('RA-EZINCPROTECTION', 'Ezinc Protection', 'ezinc-protection', 'sun-protection', 'A fast-absorbing physical block using zinc oxide, eZinc Protection is a highly protective outdoor topical, with a natural sun protection factor equivalent to a SPF 22 formula that does not leave skin white or pasty. With powerhouse antioxidants, this soothing mineral emulsion provides skin essential hydration and soothing support. Especially beneficial for thicker, more problematic skin.', 'https://cdn.shopify.com/s/files/1/0079/2828/3249/files/EZINC_PROTECTION_30ml_W.png?v=1769714552', 'https://ramarketplace.com/store/559flawless/product/ezinc-protection', 32),
  ('RA-ENZYMATICCLEANSE', 'Enzymatic Cleanse', 'enzymatic-cleanse', 'correctives', 'An active cleanser that blends pineapple enzymes and AHA’s to increase cellular exfoliation while reducing inflammation and sebum from all acne skin types. BENEFITS · Increases Cellular Exfoliation · Reduces Inflammation · Potent Blend of AHA’s · Softens Texture · Reduces Sebum', 'https://cdn.shopify.com/s/files/1/0079/2828/3249/files/ENZYMATIC_CLEANSE_120ml_3e0fe5a2-7a63-4fb4-8c35-0d7dfbf29f3e.png?v=1769632306', 'https://ramarketplace.com/store/559flawless/product/enzymatic-cleanse', 33),
  ('RA-HYLAMEGASILK', 'HylaMega Silk', 'hylamega-silk', 'correctives', 'Take hydration to a new level! This silky hydrator delivers the power of omega essential fatty acids and hyaluronic acid to deeply moisturize skin and slow the aging process. This is a must-have for any dry, pro youth evening regimen! Reduces Inflammation Binds Moisture into Skin Providing Deep Hydration Strengthens Skin Boosts Elasticity TIP: Spray skin with Cucumber Spritz prior to applying to b', 'https://cdn.shopify.com/s/files/1/0079/2828/3249/files/HYLAMEGA_SILK_SQ120ml.png?v=1781044345', 'https://ramarketplace.com/store/559flawless/product/hylamega-silk', 34),
  ('RA-KOJICCLEARMASK', 'Kojic Clear Mask', 'kojic-clear-mask', 'correctives', 'A blend of acids and healing extracts come together to reduce bacteria, blemishes and scarring. This therapeutic mask is great to use as a spot treat to disperse trapped sebum and reduce inflammation or use full-face. BENEFITS · Powerful Antibacterial Support · Lightens PIH and Suppresses Melanin · Reduces Cellular Buildup · Softens Textural Scarring · Promotes Healing of Acne Lesions', 'https://cdn.shopify.com/s/files/1/0079/2828/3249/files/KOJIC_CLEAR_50ml_W.png?v=1725470120', 'https://ramarketplace.com/store/559flawless/product/kojic-clear-mask', 35),
  ('RA-LUXECLEANSINGBALM', 'Luxe Cleansing Balm', 'luxe-cleansing-balm', 'correctives', 'With a silky, almost gel-like feel, this unique oil-based cleanser not only gently cleanses and hydrates but nourishes the skin with antioxidant support and soothing botanicals. Hydrates & Softens Skin Melts Away Makeup Uses a Natural Coconut Surfactant Pro-Youth Benefits that Leave Skin Glowing Perfect for an initial cleanse to remove makeup and buildup, it also stands alone as an essential hydra', 'https://cdn.shopify.com/s/files/1/0079/2828/3249/files/LUXE_CLEANSING_BALM_120ml_78df2b91-21c7-44d2-bc47-e0574a226bde.png?v=1769639019', 'https://ramarketplace.com/store/559flawless/product/luxe-cleansing-balm', 36),
  ('RA-ANTIOXIDANTGLOWFACIAL', 'Antioxidant Glow Facial', 'antioxidant-glow-facial', 'at-home-facials', 'An At Home Facial Collection for those clients looking for self care! Let the aroma of cherries and chocolate help clients relax and unwind. Soften skin and infuse with vital antioxidants and nutrients, revealing a hydrating glow! COLLECTION INCLUDES: Gentle Peptide Cleanse 30ml Cherry Jubilee Enzyme 15ml Chocolate Antiox Mask 15ml Grape Seed Glow 10ml', 'https://cdn.shopify.com/s/files/1/0079/2828/3249/files/ANTIOXIDANT_GLOW_HF.png?v=1769708490', 'https://ramarketplace.com/store/559flawless/product/antioxidant-glow-facial', 37),
  ('RA-BRIGHTENCLEARFACIAL', 'Brighten & Clear Facial', 'brighten-clear-facial', 'at-home-facials', 'Powerful lightening agents combined with digestive enzymes leave skin soft and brighter. Wasabi and green tea extracts combined with a replenishing grape seed serum heals acne blemishes.', 'https://cdn.shopify.com/s/files/1/0079/2828/3249/files/BRIGHTEN_CLEAR_HF.png?v=1769638724', 'https://ramarketplace.com/store/559flawless/product/brighten-clear-facial', 38),
  ('RA-PINEAPPLECLEANSE', 'Pineapple Cleanse', 'pineapple-cleanse', 'cleansers-scrubs', 'Between the aroma and the enzymatic activity this cleanser will become a staple. A blend of pineapple and ginger extracts gently softens the skin’s texture and boosts antioxidant protection for a glowing deep cleanse. Gently Exfoliates Skin Moisturizes Tissue Reveals a Luminous Complexion Leaves Skin Nourished and Radiant TIP: Use as a standalone cleanser or alternate with Antioxidant Beta Cleanse', 'https://cdn.shopify.com/s/files/1/0079/2828/3249/files/PINEAPPLE_CLEANSE_120ml.png?v=1781059727', 'https://ramarketplace.com/store/559flawless/product/pineapple-cleanse', 39),
  ('RA-PEPTIDE38', 'Peptide 38', 'peptide-38', 'peptides', 'Our most powerful peptide complex. Stimulates collagen and elastin to reduce fine lines and wrinkles and loss of firmness and elasticity. Skin will be transformed, turning back the signs of aging. Restores Hyaluronic Acid Addresses Deep Wrinkles Reduces Elastosis Powerful Neuropeptide TIP: Pair with Antiox 18 Complex for a firming/toning duo.', 'https://cdn.shopify.com/s/files/1/0079/2828/3249/files/PEPTIDE_38_30ml_T.png?v=1769706094', 'https://ramarketplace.com/store/559flawless/product/peptide-38', 40),
  ('RA-PEPTIDEMITOPROTECT', 'Peptide Mito-Protect', 'peptide-mito-protect', 'peptides', 'This potent, peptide blend fights free-radicals, leaving skin smooth, soft and radiant. With a silky texture, this product acts as a great primer before applying foundation. Collagen Synthesis Plumps Fine Lines Increases Hydration TIP: Excellent to partner with our RA IllumiColour for a beautiful pro-youth finish!', 'https://cdn.shopify.com/s/files/1/0079/2828/3249/files/PEPTIDE_MITO_PROTECT_30ml_T.png?v=1769706050', 'https://ramarketplace.com/store/559flawless/product/peptide-mito-protect', 41)
) as v(sku, name, slug, category_slug, description, image_url, external_url, sort_order)
on conflict (slug) do update set
  name         = excluded.name,
  category_id  = excluded.category_id,
  brand_id     = excluded.brand_id,
  description  = coalesce(excluded.description, public.products.description),
  image_url    = coalesce(excluded.image_url, public.products.image_url),
  external_url = excluded.external_url,
  is_retail    = true,
  -- Price and stock are the STUDIO's, not the catalogue's. This clause used to
  -- reset both to 0, which contradicted the header above and meant a re-run to
  -- refresh a photo would silently wipe every price and count in the room.
  -- They are left alone now; a fresh insert still starts at 0 (see the column
  -- list), so nothing is invented for a product that has never been priced.
  sort_order   = excluded.sort_order,
  archived_at  = null,
  is_active    = true;
